app:
  name: My app
  desc: Welcome to ${app.name}

my:
  greeting: Hello
  list:
    values: One, Two

configC : Config C — static

management.endpoints.web.exposure.include: "*"
spring:
  application:
    name: spring-config-jdbc-client #this should be same as filename of properties file in server side
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      label: latest
  profiles:
    active: dev